name: GitHub Manual Action Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
        app_type:
          description: 'cloud/inhouse'
          required: true
          type: string

jobs:
  log-dev-inputs:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'dev' }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
  log-nonprod-inputs:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'nonprod' }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
  app_cloud:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.app_type == 'cloud' }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "App type: ${APP_TYPE}"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
          APP_TYPE: ${{ inputs.app_type }}
  app_inhouse:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.app_type == 'inhouse' }}
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "App type: ${APP_TYPE}"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
          APP_TYPE: ${{ inputs.app_type }}

